### PR TITLE
Unroll group dependencies

### PR DESCRIPTION
**Pull request by sloretz**
Intended to work around https://github.com/ros2/ros2/issues/1252

### CODE REVIEW

**Comment by sloretz** [comment]
CI (build: all test: `--packages-select rosidl_default_generators rosidl_default_runtime test_msgs sensor_msgs`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16490/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11078/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16861/)

**Review by clalancette — APPROVED** [review]
This looks reasonable to me with green CI.  @nuclearsandwich @wjwwood does this match what you expect to see?

**Review by nuclearsandwich — COMMENTED** [review]
I'm conflicted about whether I think it makes sense to "unroll" groups into fine-grained dependencies or use the global `depend` key to maintain the same behavior between situations where groups are used and others.

I'm coming down currently on the side of making all unrolled dependencies plain `depend`s so that if group support became possible in tools like rosdep and bloom it would not change dependency semantics between the group dependency and unrolled group dependency.

**Review by wjwwood — APPROVED** [review]
This lgtm, as @nuclearsandwich said we might want to use `<depend>` for consistency with the behavior of the group tag, but as we're currently not doing that with what we've already unrolled I wouldn't block this on that.

**Comment by clalancette** [comment]
All right, CI is happy.  I'm going to merge this, open an issue to follow-up with @nuclearsandwich 's concerns for a follow-up, then do a release of this package onto the buildfarm to see whether this fixes the issue.

**Pull request merged**
